<a href="https://colab.research.google.com/github/tomasonjo/blogs/blob/master/dune/Cypher_v5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install neo4j

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting neo4j
  Downloading neo4j-5.4.0.tar.gz (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 KB 6.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package neo4j produced metadata for project name unknown. Fix your #egg=neo4j fragments.
Discarding https://files.pythonhosted.org/packages/01/b1/f0fe9bc5f59d54bd0ff74afdfdc58911aaab53315f2ed40087b018eb54f8/neo4j-5.4.0.tar.gz#sha256=50293f716412cc8a0fc87c364b0da105aa439859d28ffa5c89f5ca0d44514049 (from https://pypi.org/simple/neo4j/) (requires-python:>=3.7): Requested unknown from https://files.pythonhosted.org/packages/01/b1/f0fe9bc5f59d54bd0ff74afdfdc58911aaab53315f2ed40087b018eb54f8/neo4j-5.4.0.tar.gz#sha256=50293f716412cc8a0fc87c364b0da105aa439859d28ffa5c89f5ca0d44514049 has inconsistent name: filename has 'neo4j', but metadata has 'unknown'
  Downloading neo4j-5.3.0.tar.gz (157 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 157.8/157.8 KB 16.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Generating metadata for package neo4j produced metadata for project name unknown. Fix your #egg=neo4j fragments.
Discarding https://files.pythonhosted.org/packages/56/84/c4ac67441e6f2c68e859e64631d6a218a922a2aca0603dcf96ff99f17734/neo4j-5.3.0.tar.gz#sha256=0c1c7d8812eed60da0a442d1e0f35edbda248255703e506a081cb70e083b3b5c (from https://pypi.org/simple/neo4j/) (requires-python:>=3.7): Requested unknown from https://files.pythonhosted.org/packages/56/84/c4ac67441e6f2c68e859e64631d6a218a922a2aca0603dcf96ff99f17734/neo4j-5.3.0.tar.gz#sha256=0c1c7d8812eed60da0a442d1e0f35edbda248255703e506a081cb70e083b3b5c has inconsistent name: filename has 'neo4j', but metadata has 'unknown'
  Downloading neo4j-5.2.1.tar.gz (174 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.2/174.2 KB 15.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pytz in /usr/local/lib/python3.8/dist-packages (from neo4j) (2022.7)
Building wheels for collected packages: neo4j
  Building wheel for neo4j (setup.py) ... done
  Created wheel for neo4j: filename=neo4j-5.2.1-py3-none-any.whl size=249499 sha256=02f04a9170117f7aead54c6ede529f096c5592bf4f6f8c3d30d3d7c1e68c7bca
  Stored in directory: /root/.cache/pip/wheels/3f/cb/09/5c56a88c1650f9d4fe57e59d9a67a5d77fcef88f55d5c233f1
Successfully built neo4j
Installing collected packages: neo4j
Successfully installed neo4j-5.2.1

In [3]:
# Define Neo4j connections
import pandas as pd
from neo4j import GraphDatabase

host = 'neo4j+s://f4461036.databases.neo4j.io'
user = 'neo4j'
password = 'password'
driver = GraphDatabase.driver(host,auth=(user, password))

def run_query(query):
    with driver.session() as session:
        result = session.run(query)
        return pd.DataFrame([r.values() for r in result], columns=result.keys())

In [4]:
run_query("""
CREATE CONSTRAINT IF NOT EXISTS FOR (c:Character) REQUIRE c.name IS UNIQUE;
""")

Empty DataFrame
Columns: []
Index: []

In [5]:
run_query("""
LOAD CSV WITH HEADERS FROM "https://bit.ly/3kbU21V" AS row
CALL {
  WITH row
  MERGE (c:Character {name:row.Character})
  SET c += apoc.map.clean(row, ["name", "Detail", "to", "relationship_type", "House_Allegiance"], [])
  WITH c, row
  CALL apoc.create.addLabels(c, [row.House_Allegiance]) YIELD node
  CALL {
    WITH row, c
    WITH row, c
    WHERE row.to IS NOT NULL
    MERGE (c1:Character {name: row.to})
    WITH row, c, c1
    CALL apoc.merge.relationship(c, toUpper(row.relationship_type), {}, {}, c1)
    YIELD rel
    RETURN count(*) AS count
  }
  RETURN count(*) AS finalCount
} IN TRANSACTIONS OF 10 ROWS
RETURN count(*)
""")

   count(*)
0       107

In [5]:
run_query("""
MATCH (c:Fremen|Harkonnen)
RETURN count(*)
""")

   count(*)
0        16

In [6]:
run_query("""
MATCH (c:Character&Harkonnen)
RETURN count(*)
""")

   count(*)
0        15

In [7]:
run_query("""
MATCH (c:Character&!Harkonnen)
RETURN count(*)
""")

   count(*)
0        64

In [8]:
run_query("""
MATCH (c:!(Fremen|Harkonnen))
RETURN count(*)
""")

   count(*)
0        63

In [10]:
run_query("""
MATCH (c:Character WHERE c.Culture STARTS WITH "Z" AND c.Died IS NOT NULL)
RETURN c.name AS character
""")

        character
0  Ali Ben Ohashi
1         Maometh

In [11]:
run_query("""
MATCH p=(c:Character WHERE c.Culture = "Bene Gesserit")-[r:ALLIES|FAMILY]-()
RETURN [n in nodes(p) | n.name] AS pairs, type(r) AS results
""")

                                  pairs results
0  [Anirul Corrino, Shaddam Corrino IV]  FAMILY
1     [Jessica Atreides, Paul Atreides]  FAMILY
2     [Jessica Atreides, Paul Atreides]  FAMILY

In [12]:
run_query("""
MATCH p=(c:Character WHERE c.Culture = "Fremen")-[r:!(ALLIES|FAMILY)]-()
RETURN [n in nodes(p) | n.name] AS pairs, type(r) AS results
""")

                          pairs   results
0  [Chani Kynes, Paul Atreides]  MARRIAGE
1                [Geoff, Jamis]   ENEMIES
2                [Jamis, Geoff]   ENEMIES
3           [Stilgar, Tharthar]  MARRIAGE
4           [Liet Kynes, Uliet]   ENEMIES
5         [Mitha, Pardot Kynes]  MARRIAGE

In [12]:
run_query("""
MATCH p=(c:Character WHERE c.Culture = "Fremen" AND c.Died IS NOT NULL)-[r:!(ALLIES|FAMILY)]-()
RETURN [n in nodes(p) | n.name] AS pairs, type(r) AS results
""")

                 pairs  results
0       [Jamis, Geoff]  ENEMIES
1  [Liet Kynes, Uliet]  ENEMIES

In [13]:
run_query("""
MATCH (c:Character)
WHERE exists { (c)-[:FAMILY]-() }
RETURN count(*) AS count
""")

   count
0     27

In [14]:
run_query("""
MATCH (c:Character)
WHERE exists { MATCH (c)-[:FAMILY]-(t)
               WHERE (t)-[:ALLIES]-() AND (t)-[:MARRIAGE]-() }
RETURN count(*) AS count
""")

   count
0      5

In [18]:
run_query("""
MATCH (c:Character)
RETURN c.name AS character,
       count{ (c)--() } AS degree
ORDER BY degree DESC
LIMIT 5
""")

            character  degree
0       Paul Atreides      16
1     Leto Atreides I      15
2             Stilgar       7
3  Vladimir Harkonnen       6
4  Shaddam Corrino IV       6

In [15]:
run_query("""
MATCH (c:Character)
WHERE count{ (c)--() } > 2
RETURN count(*) AS count
""")

   count
0     11